# Generated by Django 3.2.16 on 2022-12-07 16:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
